services:
  interface:
    build: interface
    ports:
      - "5000:5000"
    environment:
      API_HOST: http://service:8080
    depends_on:
      - service

  service:
    build: service
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/splitast_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

      S3_URL: http://s3:9000
      S3_BUCKET: splitast-s3-dev
      S3_REGION: ru-central1
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      
    depends_on:
      - db
      - s3
#      - model

#  model:
#    build: scanityModel
#    ports:
#      - "5050:5050"
#    environment:
#      - TZ=Europe/Moscow

  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: splitast_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  s3:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
#    network_mode: host
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
#      MINIO_DEFAULT_BUCKETS: scanity-s3-dev
#    volumes:
#      - minio_data:/data
    command: server /data --console-address ":9001"




#volumes:
#
#  minio_data:
